/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import {
  Globe,
  Landmark,
  DollarSign,
  Shield,
  Settings,
  Eye,
  CheckCircle,
  Smartphone,
  Lock,
  AlertTriangle,
  Cpu,
  QrCode,
  Upload,
  RefreshCw,
  Plus,
  Trash2,
  Edit,
  Save,
  Compass,
  MessageSquare,
  Linkedin,
  Github,
  Facebook,
  Instagram,
  Twitter,
  ExternalLink,
  Moon,
  Sun,
  Copy,
  BadgeCheck,
  X,
  ChevronRight,
  Award,
  Key,
  HelpCircle,
  TrendingUp,
  History,
  Check,
  Briefcase,
  Layers,
  Sparkles,
  Search,
  CheckCircle2,
  FileText,
  Mail,
  Youtube,
  Send,
  Users,
  Phone,
  Calendar,
  Trophy,
  MapPin,
  Music,
  Image,
  Video,
  Link
} from 'lucide-react';

const iconsMap: Record<string, React.ComponentType<any>> = {
  globe: Globe,
  landmark: Landmark,
  dollarsign: DollarSign,
  shield: Shield,
  settings: Settings,
  eye: Eye,
  checkcircle: CheckCircle,
  smartphone: Smartphone,
  lock: Lock,
  alerttriangle: AlertTriangle,
  cpu: Cpu,
  qrcode: QrCode,
  upload: Upload,
  refreshcw: RefreshCw,
  plus: Plus,
  trash2: Trash2,
  edit: Edit,
  save: Save,
  compass: Compass,
  messagesquare: MessageSquare,
  linkedin: Linkedin,
  github: Github,
  facebook: Facebook,
  instagram: Instagram,
  twitter: Twitter,
  externallink: ExternalLink,
  moon: Moon,
  sun: Sun,
  copy: Copy,
  badgecheck: BadgeCheck,
  x: X,
  chevronright: ChevronRight,
  award: Award,
  key: Key,
  helpcircle: HelpCircle,
  trendingup: TrendingUp,
  history: History,
  check: Check,
  briefcase: Briefcase,
  layers: Layers,
  sparkles: Sparkles,
  search: Search,
  checkcircle2: CheckCircle2,
  filetext: FileText,
  mail: Mail,
  youtube: Youtube,
  send: Send,
  users: Users,
  phone: Phone,
  calendar: Calendar,
  trophy: Trophy,
  mappin: MapPin,
  music: Music,
  image: Image,
  video: Video,
  link: Link
};

interface LucideIconProps {
  name: string;
  className?: string;
  size?: number | string;
}

export default function LucideIcon({ name, className = '', size = 20 }: LucideIconProps) {
  const iconKey = name.toLowerCase().trim();
  const IconComponent = iconsMap[iconKey] || Globe;
  return <IconComponent className={className} size={size} />;
}
